// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetHello(arg1) {
  return window['go']['main']['App']['GetHello'](arg1);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function NowTime() {
  return window['go']['main']['App']['NowTime']();
}
