// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetHello(arg1:string):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function NowTime():Promise<string>;

export function SaveCardSettings(arg1:Array<main.CardIDSettings>):Promise<void>;
